### ISSUE TITLE
Document use of far

### ISSUE THREAD

**Issue by tyg** [Agoric/documentation#456]
Please write up a few paragraphs about 1) What is far()/what does it do? 2) When should you use it when programming JS for Agoric? Concret examples as well as general scenarios are good. Thanks.

**Comment by tyg** [comment]
Certain objects are "Remotable": they have methods that can be invoked remotely (across contracts and vats), using the `E()` syntax. These objects also have an "interface name" associated with them, which is useful for debugging. All objects used in the external API of your contract must be Remotable.

For an object to qualify as Remotable, four requirements must be met:

* each property name on the object is a String, not a Symbol (except for AsyncIterator)
* each property value must be a function: not an accessor (getter/setter), not plain data
* the object must be `harden()`ed
* the object must be marked with `Far` or `Remotable`

The simplest way to mark an object as Remotable is to use the `Far()` function. This performs `harden()` and checks the object for the requirements above right away, and it also records the interface name. You'll use it like this:

```js
import { Far } from '@agoric/marshal';
let counter;
const countRemotable = Far('counter', {
  increment() { counter++; },
  decrement() { counter--; },
  read() { return counter; },
});
```

When `countRemotable` is exported from your contract and delivered to some remote vat, they will receive a Presence. The recipient can use `E(countPresence).increment()` to increment the counter. If they do a `console.log(countPresence)`, the object will be labeled as a Presence whose alleged interface name is "counter".

The `Remotable()` function is a lower-level way to apply the same Remotable label that `Far()` provides, but the API is less convenient. In older code, before `Far` was required, you may see a pattern like this:

```js
let counter;
const countRemotable = harden({
  increment() { counter++; },
  decrement() { counter--; },
  read() { return counter; },
});
```

In most cases, this code can be upgraded by simply replacing the `harden(..` with `Far('interfacename' ..`.

Note that in the future, this code will cause an error when `countRemotable` serialized for transmission. At that point, `Far()` must be used.

**Comment by warner** [comment]
`They cannot be either an accessor (getter/setter) or plain data.`: that feels awkward to me, because of the negative, I'd remove the `either`, or make it `can be neither X nor Y` but then the `They can` feels awkward because it's too positive.

@erights am I getting the `AsyncIterator` part right? I'm not remembering what we implemented now.

* 1: Yep, `Far` takes an interface name and the object-with-methods being exported
* 2: On the exporting side, the object-with-methods is called a remotable. When you send this remotable to a different vat (as the argument of some method, or in the resolution of a promise), it arrives as a Presence. So the side which is invoking `increment` *remotely* is doing it on a Presence, with `E()`. I meant `countRemotable` and `countPresence` as a form of type indicator, but I'll admit it's grammatically ambiguous ("count" sounds like a verb). Maybe we should use "remotableCounter" and "presenceCounter"? Except we aren't counting presences. Maybe we need an example whose core isn't so verb-like. "fooPresence" and "fooRemotable" might be less misleading.
  * we could potentially expand the example to show how the remotable got sent out, and how it got received by the Presence side, but that seemed like a distraction at the time
* 3: I think it throws an error, but I'll leave that to @erights 
* 4: I believe the interface name only shows up in console.log. It also appears in the `toString()` value, so user-level code could conceivably learn it and react to it, but our intention is that it's only for debugging, not program logic.
* 5: Good point. Yes, Far() automatically does harden(), so if you're creating a remotable, you only have to do Far(). If you're sending *data*, then you must still use `harden()`, because there's no equivalent `Data()` (well, there was, but we removed it). Hardening data is a bit of a gray area because most of our message-passing code automatically hardens any arguments you pass into the `E()` call, or use as a promise resolution. This makes @erights squirm because it's a quiet side-effect. If I understand his feelings correctly, and @erights please tell me if I'm wrong, he'd either prefer that user-level code be required to call `harden()` on everything itself, or that we use something like Jessie which might(??) automatically `harden` data when it leaves some setup scope.

For now, `harden()` is used to protect data created by one function against surprising mutation by some other function in the same vat. You can, but are not currently required to, `harden()` data before putting it in an `E()` argument or promise resolution.

BTW I'm not 100% sure how to name this object-with-methods thing. I've used "remotable" as a generic noun here, we could also call it "pass-by-reference" but that's a mouthful. Whatever this thing is, you create one with either `Far()` or `Remotable()` (and `Far` is the easier one to use, because the arguments are in a nicer order). I didn't want to call them "Far", because at the time you create/mark one, you're holding the thing directly: it isn't far away from *you*, it will be far away from the remote vat that you send it to (all Presences are far references to some other vat's local thing that was made/marked with `Far()`). There's a consistent grammar in here somewhere but I'm not sure what it is yet.

**Comment by tyg** [comment]
> * 2: On the exporting side, the object-with-methods is called a remotable. When 
> you send this remotable to a different vat (as the argument of some method, or 
> in the resolution of a promise), it arrives as a Presence. So the side which is invoking 
> `increment` _remotely_ is doing it on a Presence, with `E()`. I meant `countRemotable` 
> and `countPresence` as a form of type indicator, but I'll admit it's grammatically 
> ambiguous ("count" sounds like a verb). Maybe we should use "remotableCounter" 
>and "presenceCounter"? Except we aren't counting presences. Maybe we need an 
> example whose core isn't so verb-like. "fooPresence" and "fooRemotable" might be less misleading.

I'm still not quite clear here. Going back to the original example code and following comments:
-----------
```js
import { Far } from '@agoric/marshal';
let counter;
const countRemotable = Far('counter', {
  increment() { counter++; },
  decrement() { counter--; },
  read() { return counter; },
});
```
When countRemotable is exported from your contract to a remote vat, the vat receives a Presence. It can use E(countPresence).increment() to increment the counter. If they do a console.log(countPresence), the object is labeled as a Presence whose alleged interface name is "counter".

------------------

What I'm not clear on is how/why we went from `countRemotable` being defined as a Farified object to talking about `countPresence` Did the name somehow change? Was countPresence auto-created at some point or is this a new definition by a developer?

**Comment by warner** [comment]
Nope, `countRemotable` is in one vat (the one where `Far` was called), while `countPresence` is its counterpart in a second vat (where `E()` is being called). A fuller example would looke like this:

```js
// vat 1
import { Far } from '@agoric/marshal';
export function buildRootObject() {
  let counter;
  const fooRemotable = Far('counter', {
    increment() { counter++; }
  });

  return Far('root', {
    getFoo() {
      return fooRemotable;
    },
  });
}
```

```js
// vat2
async function run(vat1RootObject) {
  const fooPresence = await E(vat1RootObject).getFoo();
  E(fooPresence).increment();
}
```

A completely full example would need to explain how `run()` got called, and how it came to be given `vat1RootObject` (which is also a Presence, a second one, which is linked to the `Far('root')` returned by vat1's `buildRootObject`). It's turtles all the way down, or in this case it's objects all the way up. As @erights says, "connectivity begets connectivity". You start with one object reference (a Presence) via some magic bootstrapping process, and then you acquire more Presences by sending messages through that one, or through the objects that come back, or in messages sent to objects (Remotables) that you share through other messages, etc.

A Far/Remotable can be sent out of its defining/exporting vat, in a message to some other vat, or as the resolution of a Promise (in this case, the implicit result promise of `getFoo()`). When that message/resolution arrives in the other vat, a Presence is created. So inside vat1, `fooRemotable` is serialized into an identifier when `getFoo()` returns it as a value. Inside vat2, the `E(vat1RootObject).getFoo()` call returns a Promise, and that Promise resolves to a Presence that contains the same identifier. This identifier is what allows the subsequent `E(fooPresence).increment()` call to refer to the right object (the `increment` message is sent from vat2 back to vat1, where it invokes the `.increment()` method on `fooRemotable`).

**Comment by erights** [comment]
> `They cannot be either an accessor (getter/setter) or plain data.`: that feels awkward to me, because of the negative, I'd remove the `either`, or make it `can be neither X nor Y` but then the `They can` feels awkward because it's too positive.
> 
> @erights am I getting the `AsyncIterator` part right? I'm not remembering what we implemented now.

I assume you're asking about

> * Each of its property names is a String. They cannot be a Symbol (except for AsyncIterator),
> * Each of its property values is a function. They cannot be an accessor (getter/setter) or plain data.
> * It must be harden()ed.
> * It must be marked with Far() or Remotable().

All except the first. It can in fact have symbol-named function properties for any symbol. However, the only symbol you can send through our system (both marshal and as a method name in swingset) is `Symbol.asyncIterator` so any method named by any other symbol would not be remotely invokable.


> 
> * 1: Yep, `Far` takes an interface name and the object-with-methods being exported
> * 2: On the exporting side, the object-with-methods is called a remotable. When you send this remotable to a different vat (as the argument of some method, or in the resolution of a promise), it arrives as a Presence.

This is how we have come to talk about these informally, and I think we should continue to do so, including in our user-level documentation, because it is the least confusing without getting into the subtlelies.

The subtleties that we need to consider in choosing precise meanings for these terms: (attn @michaelfig )
* Is a remote presence also a "remotable"?
* Is the local exported remotable also a "presence"?
* Eventual-send/handled-promise is at a lower level of abstraction than marshal. Eventual-send/handled-promise introduces the concept of presence, but not all uses of its presences are necessarily to support marshal's use of them for the remote presences of remotable objects.

> So the side which is invoking `increment` _remotely_ is doing it on a Presence, with `E()`. I meant `countRemotable` and `countPresence` as a form of type indicator, but I'll admit it's grammatically ambiguous ("count" sounds like a verb). Maybe we should use "remotableCounter" and "presenceCounter"? Except we aren't counting presences. Maybe we need an example whose core isn't so verb-like. "fooPresence" and "fooRemotable" might be less misleading.

Given the above understanding of the terms, normal code should never refer to something as a "presence" because then the code only makes sense when in a vat that is remote from the remotable being referenced. Normal code should instead distinguish only "thing I know to be local" such as a "remotable" vs "thing that may be a local remotable or be a presence of a remote remotable". Without visiting the subtleties above, we don't have a name for the latter concept.

Put another way, any code written assuming it is operating on a presence of a distant object should still work when co-located with that object. 

>   * we could potentially expand the example to show how the remotable got sent out, and how it got received by the Presence side, but that seemed like a distraction at the time
> * 3: I think it throws an error, but I'll leave that to @erights

Yes it throws.

> * 4: I believe the interface name only shows up in console.log. It also appears in the `toString()` value, so user-level code could conceivably learn it and react to it, but our intention is that it's only for debugging, not program logic.

Yes. In particular, the interface name found on a presence is currently unreliable; it may not be according to the remotable object it is a presence for. Hence our current insistence that these strings contain "Alleged: ". @warner , this is part of the problem to be fixed by your "auxiliary data".

> * 5: Good point. Yes, Far() automatically does harden(), so if you're creating a remotable, you only have to do Far(). If you're sending _data_, then you must still use `harden()`, because there's no equivalent `Data()` (well, there was, but we removed it). Hardening data is a bit of a gray area because most of our message-passing code automatically hardens any arguments you pass into the `E()` call, or use as a promise resolution. This makes @erights squirm because it's a quiet side-effect. If I understand his feelings correctly, and @erights please tell me if I'm wrong, he'd either prefer that user-level code be required to call `harden()` on everything itself, or that we use something like Jessie which might(??) automatically `harden` data when it leaves some setup scope.

Only hardened objects are passable. User code should ensure that only passable objects are passed. Our message passing code should indeed be fixed to reject non-passables by throwing an error. User code should assume that this change is coming.

> 
> For now, `harden()` is used to protect data created by one function against surprising mutation by some other function in the same vat. You can, but are not currently required to, `harden()` data before putting it in an `E()` argument or promise resolution.

I would add that you are encouraged to harden objects that you create before you release them, as part of encouraging defensive programming in general. A non-hardened object cannot defend itself from its clients.

> 
> BTW I'm not 100% sure how to name this object-with-methods thing. I've used "remotable" as a generic noun here, we could also call it "pass-by-reference" but that's a mouthful. Whatever this thing is, you create one with either `Far()` or `Remotable()` (and `Far` is the easier one to use, because the arguments are in a nicer order). I didn't want to call them "Far", because at the time you create/mark one, you're holding the thing directly: it isn't far away from _you_, it will be far away from the remote vat that you send it to (all Presences are far references to some other vat's local thing that was made/marked with `Far()`). There's a consistent grammar in here somewhere but I'm not sure what it is yet.

We should call these "remotables" unless @michaelfig disagrees.

**Comment by erights** [comment]
The following is the terminology @michaelfig and I agreed on. Switching to this or something like it will be tricky. But switching to terminology with these distinctions and precision is necessary, and this is the best we could come up with for being precise and informally understandable at the same time. We're certainly open to improving on this, but let's start here.

Marking an object with the `Far` or `Remotable` functions makes that object a *primary*, which is a kind of *remotable*. When emphasizing both attributes, we can also call that object the *primary remotable*.

When a *primary* is passed as an argument in a message to a remote object, i.e., an object in another vat, what arrives in that other vat is a *remote*, which is also a kind of *remotable*. These are the only kinds of *remotable*: *primaries* and *remotes*. A *primary* can have any number of corresponding *remotes*. Each *remote* has exactly one corresponding *primary*.

All *remotables* are *pass-by-remote*. When a (primary or remote) *remotable* is passed as an argument, a corresponding (primary or remote) *remotable* arrives in the message as delivered.

Using the `E` syntax, one may send an async message to a *remotable*. That message will be delivered to that *remotable*'s *primary*.

Only *passable* values that may be passed as arguments in messages to remote objects. *Remotables* are *pass-by-remote* *passables*. Primitive data values like numbers are strings, as well as hardened arrays and data records are *pass-by-copy* *passables*, and arrive as a local copy of that value. Promises are also *passable* and arrive as promises.

Only *hardened objects* can be *passable*, i.e., all *passables* are *hardened* and *non-hardened objects* are not *passable*. Objects may be *hardened* by the `harden`, `Far`, or `Remotable` functions.

**Comment by warner** [comment]
Incidentally, within my corner of the system I find a need to distinguish between "imports" and "exports" a lot. We usually export the remotables. Presences are always imports. The "representatives" you get for virtual objects are things you can export, or just use locally.

**Comment by erights** [comment]
Should this now be closed?

**Comment by tyg** [comment]
Yep.
